honeycombio/husky

otlp/trace.go
otlp/trace_test.go

`BytesToTraceID` is a useful utility that is used to convert a TraceID encoded as a []byte to a hex string. Making it public would allow users of the module to use it when verifying data.
- make BytesToTraceID public and update internal usage

Make bytesToTraceID public

---

otlp/common.go
otlp/common_test.go
otlp/errors.go
otlp/errors_test.go
otlp/trace.go
otlp/trace_test.go

Adds new `OTLPError` struct that contains a message, HTTP and GRPC status codes. Created reusable errors for standard use cases (content type, required headers, etc).
- Add new `OTLPError` type
- Add standard errors for content-type, required headers, etc
- Return new errors from trace and common funcs

Add error support

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/pull_request_template.md
.github/workflows/add-to-project.yml
.github/workflows/apply-labels.yml
.github/workflows/stale.yml
LICENSE
README.md

Updates the repo to have standard OSS workflows, issue templates, codeowners, license, etc.
- Adds Apache2 `LICENSE`
- Sets CODEOWNER to @honeycombio/telemetry-team 
- adds PR issue template
- adds github workflows

Update repo to have standard OSS issues templates, codeowners, workflows, etc

---

otlp/common.go
otlp/common_test.go

Adds support for receiving and JSON stringifying array and KV list attributes.
- Resolves https://github.com/honeycombio/telemetry-team/issues/88
- adds support for converting array and kv list attributes and generating JSON strings

Add support for array and KV list attributes

---

otlp/common.go
otlp/common_test.go

Handle scenario where a KeyValue's value field is nil.
- Closes https://github.com/honeycombio/refinery/pull/358
- Check the attribute value is not nil before trying to use it
- Add unit test

Handle KeyValue attributes with nil value

---

otlp/README.md
otlp/common.go
otlp/common_test.go
otlp/trace.go
otlp/trace_test.go

Updates husky interface to not require http.Request object and offers overloads that take `http.Header` or `io.BodyCloser` objects. This improves compatibility of consumers.
- move validate content type into validate headers
- update `GetRequestInfoFromHttpHeaders` to take `http.Header` instead of `http.Request`
- update `TranslateHttpTraceRequest` to take `io.BodyCloser` and `RequestInfo` instead of `http.Request`

Remove dependency on http.Request

---

otlp/trace.go
otlp/trace_test.go

Update both `TranslateHttpTraceRequest` & `TranslateGrpcTraceRequest` to return a known struct instead of a `map[string]interface{}`. Extend return struct to parse sampleRate attribute and calculate and return trace request size.
- Closes #21 
- Closes #22 
- Add `TranslateTraceRequestResult` and `Event` structs
- Return new structs as part of `TranslateHttpTraceRequest` & `TranslateGrpcTraceRequest` calls
- Extract sampleRate attribute and set on return struct
- Add tests for converting sample rate types, default values, etc
- Gets the request size using `proto.Size(request)` and sets on return struct
- Update tests to ensure the correct size is returned

Update translate trace request calls to return struct instead of params

---

otlp/trace.go
otlp/trace_test.go

Records the number of span events and span links in the parent span as attributes.
- Adds new attributes to record span links and event counts
- Add test to ensure attribute is set

Record number of span events and links

---

otlp/common.go
otlp/common_test.go

Adds support for paring and returning the proxy version as part of RequestInfo struct.
- Closes #25 
- Parses the `x-basenji-version` header and sets RequestInfo.ProxyVersion field

Parse proxy version as part of RequestInfo

---

CHANGELOG.md
RELEASING.md
version.go
version_test.go

Adds versioning info to easily identify module version at runtime, eg to add to telemetry.
- Adds version.go that holds version number (currently set to latest release `0.5.0`)
- Updates RELEASING doc
- Fix spacing issue in changelog

Add versioning info

---

otlp/common.go
otlp/common_test.go
otlp/errors.go
otlp/trace.go
otlp/trace_test.go

- support environment-aware OTLP instrumentation
- updates https://github.com/honeycombio/telemetry-team/issues/173
- breaking changes!
- ~~ValidateHeaders~~ >> ValidateTracesHeaders, ValidateMetricsHeaders
- TranslateTraceRequest will now return a map of dataset:[events], and will decide if the dataset should come form the metadata/header (legacy) or the service.name attribute

feat!: environments & services support

---

otlp/common.go
otlp/trace.go
otlp/trace_test.go

- shepherd needs to track how big each request is per dataset
- https://houndsh.slack.com/archives/C015UD6R8PJ/p1643848568491229
- approximating each dataset batch size to be `proto.Size(resourceSpan)`
- previously, `proto.Size(otlpRequest)` would be used in the same stat for the single dataset in the header

feat!: include individual batch sizes

---

.editorconfig

- editorconfig indent style conflicts with `go fmt` standard (tabs)
- defer to go fmt (which formats with tabs)

maint: remove indent style from editorconfig

---

otlp/errors.go
otlp/trace.go
otlp/trace_test.go

- closes #41 
- Most SDKs will add a default service name if none are provided (`unknown_service:java`, etc). But in the (hopefully rare) scenario that a service name is missing or is an empty string, we should set the missing service name to `unknown_service`.
- this attempts to use `service.name` string value found in resource attributes. Service name will default to `unknown_service` if:
- missing service name key or value in resource attributes
- service name value is an empty string
- service name value is not a string
Confirmed when sending empty service name string using otel-cli, no longer get "unable to resolve dataset error". Data is sent and new service name created `unknown_service`.

empty or missing service name should default to unknown_service

---

otlp/trace.go
otlp/trace_test.go

- unknown service attribute can have unfriendly characters making it turn into a weird dataset once slugified
- updates #45 
- if resource attribute starts with `unknown_service` --> truncate the dataset to just `unknown_service`
- event attribute is still the full resource attribute value

feat: truncate dataset name when service is unknown

---

otlp/common.go
otlp/common_test.go

- we want mis-configured metrics to end up in an `unknown_metrics` dataset (when using a non-legacy API key)
- updates https://github.com/honeycombio/telemetry-team/issues/188
- validate metrics header is now (again) the same as validate traces headers, but I don't want to break the API (again) by consolidating the two functions into one. we can consolidate them in the future once the dust settles.
- add test granularity to make the results more readable

feat: update metrics header validation

---

otlp/trace.go
otlp/trace_test.go

- misconfigured service.name, such as ` ` or `\tmy-service\t`, when used as the dataset name, will result in weird behavior in the product (URL dataset will be a slug, hard to tell there's whitespace in the UI)
- updates https://github.com/honeycombio/telemetry-team/issues/196
- trim service.name value prior to applying it as the dataset

feat: trim dataset when deriving from service.name

---

.circleci/config.yml

Fixes Circle CI publish_github job filters to run for tags. Job creates a draft github release.
- Closes #44 
- Closes #37 
- Updates the _publish_github_ Circle CI job to apply valid filter

Update publish github filters in CircleCI config

---

otlp/trace.go
otlp/trace_test.go

Our documentation states that sample rate is optional and defaults to 1. 
Our code uses a go int value for sample rate, and believes that the default zero value and omitted sample rates are the same. 
Our instrumentation shows sample rate as either 0 or 1, confusing the people reading the instrumentation and making math on sample rates difficult. (AVG(app.sample_rate) is not accurate because of mixed 0s and 1s influencing the average but not changing the system's behavior.)
Otel documentation has a [different meaning for zero](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/tracestate-probability-sampling.md#adjusted-count), but that's not how our system works. That they're different leads to confusion.
To clarify the current behavior for people …

default sample rate to 1 if omitted or if 0

---

go.mod
go.sum

Update OTLP proto to v0.11.0 to match Honeycomb API.
- Update otlp-proto-go to v0.011.0

Update OTLP proto to v0.11.0

---

otlp/trace.go
otlp/trace_test.go

- #68 
- add a test for spans from multiple libraries in a single batch
- change from setting `library.(name|version)` via `resourceAttrs` to setting on each event

Fix library.version spillover between spans in a single batch

---

otlp/trace.go

Ensures span attributes are preserved in favour of resource attributes that has the samekey. The current behaviour has resource attrs preserved.
- Closes #73
- Copy span attributes after resource attrs, they go into the same map so attrs with the same key are overwritten

Copy span attrs after resource attrs

---

otlp/trace.go
otlp/trace_test.go

**Sign/Symptom:** 
A customer reported that `status_code` values had stopped appearing abruptly in one of their datasets. They had changed the type of the `status_code` column in the dataset schema from string to integer. _This is a totally reasonable thing to do because an OpenTelemetry span status code is an integer._
**Origin:**
Prior to this change, Husky sets `status_code` to a `trace.Status_StatusCode` type from the trace.pb.go generated from OTLP proto definitions. For Reasons™, that type _would_ convert to a string during our data ingest, but would _not_ convert to an integer (despite the type's association with actual `int32` constants).
We'll now do the type conversion from OTLP proto enum shenanigans to an `int` here in husky's transform of an OTLP span into an event. The …

Convert OTLP span status.code type to integer earlier in the transform

---

otlp/common.go
otlp/logs.go
otlp/traces.go

Renames the TranslateTraceRequestResult struct to be generic.
- Closes #89
- Rename TranslateTraceRequestResult to TranslateOTLPRequestResult
- Add missing description to ValidateLogsHeaders func

Rename translate OTLP request structs to be generic

---

otlp/logs.go
otlp/logs_test.go

It's important that meta.annotation_type is only set when a log is part of a trace, otherwise data can look strange in datasets that only contain logs.
- Only set the meta.annotation_type field when the log has a trace ID associated to it
- Add unit test to verify annotation_type is set correctly

Only set meta.annotation_type field when log is part of trace

---

otlp/common.go
otlp/logs.go
otlp/logs_test.go
otlp/traces.go
otlp/traces_test.go

Scope attributes were being carried over between scope entries which can lead to incorrect attributes being added to events. This change introduced a new utility func that extracts resource attributes and scope attributes and returns a new map[string]interface{} which is run per
- add getDataset to remove duplicate code
- move defaultService const to common
- make IsLegacy func a RequestInfo member
- add getResourceAttributes and getScopeAttributes utility funcs
- make sure we always apply attributes in order - resource ->  scope -> span/log

Don't duplicate scope attributes between scopes

---

otlp/common.go
otlp/common_test.go
otlp/logs.go
otlp/logs_test.go
otlp/traces.go
otlp/traces_test.go

This PR adds support for translating OTLP/JSON trace and log requests. This is achieve by checking the contentType header and using `protojson.Unmarshal` to decode the request into a protobuf message.
- Update trace and log header validation to allow application/json
- Use content type header to switch between protobuf and json unmarshal when decoding HTTP body
- Extend trace tests to test both protobuf and json requests can be decoded with different encodings 
- Add log tests to verify log requests can be decided with different encoding

Add support for translating otlp/json trace and log requests

---

otlp/common.go
otlp/common_test.go
otlp/common_testhelpers.go
otlp/errors.go
otlp/logs_test.go
otlp/traces_test.go

Enabling support for all the OTLP content types. The ingest for metrics is still handled elsewhere at the moment, but that process uses husky's header validation before proceeding, so allowing JSON needs to happen here first.
* Refactored how supported content types are checked. A list of supported types is declared once and public function is provided to check for the presence of a given type in the supported list.
* A note here that all three signals have the same validation implementation which I suspect may remain true for husky's level of abstraction. We could consider consolidating them down to one function.
* Bonus: included a correction to the HTTP error we return when a content type is not supported: [415 Unsupported Media …

[feat] allow OTLP/http-json for metrics

---

.circleci/config.yml
.gitignore
Makefile
otlp/common.go
otlp/common_test.go

Our request header validation rules differ between OTLP Logs, Metrics, and Traces. We'll need to undo the consolidation of the validation logic done in #121. 🤭 
* Metrics didn't cover "E&S key, no dataset" case.
* There didn't appear to be tests for validating log requests.

[fix] unconsolidate header validation

---

otlp/common.go
otlp/common_test.go

More fallout from the header validation [consolidation](https://github.com/honeycombio/husky/pull/121/commits/3cba35dc0d16d840ee26c00ed9a3e5782b78cc29)-and-[diaspora](https://github.com/honeycombio/husky/pull/122).
E&S environments are not *required* to set x-honeycomb-dataset header; we have a fallback for them. Classic teams must provide a target dataset.

[fix] only classic teams must provide a dataset header when sending metrics

---

otlp/common.go
otlp/traces_test.go

- discovered when looking at unwrapped error handling in the API
- gzip.NewReader and zstd.NewReader return (nil, err) when there is an error
- we can only defer closing them if we got back a reader, otherwise we get a nil pointer
- only call close() on readers we know exist

fix: avoid nil pointer

---

otlp/common.go
otlp/traces_test.go

- Missed detection of Java instrumentation
- Updates instrumentation prefix for Java instrumentation library names to be `io.opentelemetry` instead of `io.opentelemetry.instrumentation`
- Updates test for known value of an instrumentation library
Instrumentation for Java does not include `instrumentation` as part of its resource span name. Instead, it is `io.opentelemetry.<library>-<version>`. The [instrumenter](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/instrumenter/Instrumenter.java) also includes the library version as part of the library name.

fix: update java library name prefix

---

otlp/common.go
otlp/traces_test.go

- Missed detection of .NET instrumentation
- Updates instrumentation prefix for .NET instrumentation library names to be `OpenTelemetry.Instrumentation` instead of `opentelemetry.instrumentation`.
- Updates test for known value of an instrumentation library
While the instrumentation prefix is the same for both python and .net, case sensitivity makes them differ. Another option here could be to lowercase them, but this matches the string the way it's written today.

fix: update dotnet library name prefix

---

otlp/common.go
otlp/traces_test.go

- #170 left OTel Ruby auto-instrumentation libraries undetected
- The OTel Ruby auto-inst libraries [report their scope/library name as a fully qualified Ruby class/module namespace string](https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-ruby-contrib%20library.name&type=code).

fix: correct Ruby library/scope name prefix

---

otlp/traces.go

OTLP/JSON data coming direct from browser sources is arriving with traceID and spanID encoded as hex, [per spec](https://opentelemetry.io/docs/reference/specification/protocol/otlp/#json-protobuf-encoding). 
But when this is fed through the OTLP protojson library that Husky uses, these values are being decoded [as if they were encoded in base64](https://go.dev/play/p/rhP_HnZ2o3n).
The result is that Husky is corrupting these IDs.
- This adjusts the `BytesToTraceID` function and adds `bytesToSpanID` to special-case the conversion (which we can detect by its length).

fix: Proposed fix for JSON ingestion issue

---

otlp/traces.go
otlp/traces_test.go

- The bug fix in #179 had a bug, and it was found by a test in an internal library before deploy. 
- Fix bug in BytesToTraceID
- Add a test that would have found the bug, and more test cases for the new stuff
This requires a release to v0.22.1.

fix: Fix bug in BytesToTraceID, add test for it.

---

otlp/traces.go
otlp/traces_test.go

- Ingesting base64-encoded spanIDs emitted from browsers
- follow-up to #182 
- Added a test to demonstrate the issue
- `:=` -> `=` to fix unintended variable scoping

fix: ingest base64-encoded spanIDs from browsers

---

otlp/traces.go

- follow-up to #184 
- Parse parent span IDs like we do span IDs to deal with base64 shenanigans

fix: ingest munged parent span IDs

---

CHANGELOG.md
version.go

Prep release of v0.22.2.
Also fixes some missed attribution links in the changelog.

rel: Prep v0.22.2

---

otlp/common.go
otlp/common_test.go

- Honeycomb has ended the life of its secure tenancy proxy. The headers associated with it are now obsolete.
- Remove refs to and tests for `x-honeycomb-proxy-token` and `x-basenji-version`.

maint: Remove refs to proxy token and headers

---

otlp/traces.go
otlp/traces_test.go

This came from a discussion and screen share with @puckpuck
So, today, as we know, exceptions get captured as span events with OTel. That's fine.
However, it's not so fine for us, namely:
1. Querying them is a little awkward since you're often looking/caring about spans, but you need to actually query the span events. This makes it harder to do bubble ups and see what error/exception info differs.
2. Digging into a trace with an error yields no data on the span; you need to click into the span events tab (which people often miss!) and then find the span event that has the error details (there can be several that have no errors) and _then_ you can see the actual exception detail
This solves both problems by copying the exception details onto the parent span that has those events.

feat: copy exception details from span event to parent span

---

.github/dependabot.yml

- dependabot still notifies telemetry when it opens PRs

maint: update dependabot config

---

.gitignore
otlp/common.go
otlp/common_test.go

OTLP HTTP protocol is very specific with how a server should respond to a client. This PR adds new functions to help handle OTLP HTTP response requirements:
1. Must set the content type to match in request content type
2. A status code must be set
3. For Success, a the response body MUST be a `Export[Trace|Metrics|Logs]ServiceResponse` with a nil PartialSuccess.
4. For errors, the response body MUST be a [Status](https://pkg.go.dev/google.golang.org/genproto/googleapis/rpc/status#Status).
See https://github.com/open-telemetry/opentelemetry-proto/blob/main/docs/specification.md#otlphttp for full requirements.
- Adds several new functions to help users respond to HTTP OTLP requests.
- Adds new unit tests for these functions.

feat: Add public functions for handling OTLP HTTP responses

---

otlp/common.go

- `WriteOtlpHttpResponse` did a no-no where it could return an error after writing a status code to the Writer.  This makes it really hard for users to know the state of their Writer once the call to `WriteOtlpHttpResponse` ends.
- Update function order to no longer error once we've written a status code.
- Updates the comments.

fix: bug where we could error after writing a status code

---

otlp/common.go
otlp/common_test.go
otlp/logs.go
otlp/traces.go
otlp/traces_test.go

- In https://github.com/honeycombio/husky/pull/179 we added some code to deal with the fact that OTLP/JSON  processing can't differentiate between arrays of bytes that are encoded as hex and those that are encoded as base64. When JS sends us browser-side telemetry, it encodes IDs as hex, but when we receive it it's decoded as base64. This PR also applies that to logs.
- Adjust log's parentID so that it properly parses
- Add a new test case
- Move some code to common since it now applies across signals
- Move some tests to common
- Clarify some comments

fix: properly parse parent id for logs

---

otlp/traces.go

- #211
- Check for negative value and use 0 instead
- Add `meta.negative_duration = true` if that happens
Closes #211

fix: Handle case of endtime before starttime

---

.github/dependabot.yml

- dependabot had the wrong team name
- fix the team name

chore: fix team name for dependabot

---

otlp/README.md

Skip changelog, etc -- fixes a cosmetic defect in the docs.

docs: fix typo in section heading

---

otlp/common.go
otlp/common_test.go
otlp/logs.go
otlp/logs_test.go
otlp/traces.go

When translating OTLP kv lists we currently just encode as a JSON string which isn't particularly useful. This PR extends the extraction behaviour to traverse kv lists to generate multiple event fields. The max depth is set to 5 levels.
For example, this kv attribute:
```
key: "data"
value: {
"key1": "val1",
"key2": true,
}
```
Previously would be stored like this:
```
data: "{\"key1\": \"val1\","key2":true}"
```
After the change, the same kv list would be stored like this:
```
data.key1: "val1"
data.key2: true
```
This change exposes the `AddAttributesToMap` func for consumers to use directly. This will be useful until metrics translation can be moved into this library (eg from shepherd).
- Closes #235 
- Update logic to extract OTLP data types to traverse kv lists instead of always …

feat: Allow flattening of OTLP key-value lists

---

otlp/common.go
otlp/common_test.go

Updates the error handling logic to check if the error is from an invalid content type first. This is necessary to ensure we can successfully create a valid OTLP response. This needs to be first because it determines how we present any errors back (eg invalid API ket).
This PR also updates WriteOtlpHttpFailureResponse to check if the error is an invalid content type, and write a text/pain response if true. This removes the need for consumers of this function to have to do it themselves.
- Update each signal's validate headers function to check content type first
- Update `WriteOtlpHttpResponse` to check if the content type is valid, if not writes a HTTP status code 415 text/plain error response instead
- Update tests

fix: Handle invalid content type errors first

---

.github/dependabot.yml

Reduce the number of dependabot PRs
- Groups minor and patch dependency updates into a single group.

maint: group dependency updates

---

otlp/common.go
otlp/common_test.go
otlp/logs.go
otlp/logs_test.go
otlp/traces.go
otlp/traces_test.go
telemetry.go

Adds tracing support to Husky that can be configured by library users (eg beeline or otel). This is done by exposing a new global var `AddTelemetryAttributeFunc` that husky will call internally. The new func receives a context struct and a map of attributes with the library responsible to setting that telemetry on whatever telemetry client being used.
For example, a library user may configure the beeline then set the `AddTelemetryAttributeFunc` to add the attributes to the current beeline span like this:
```golang
husky.AddTelemetryAttributeFunc = func(ctx context.Context, key string, value any) {
beeline.AddField(ctx, key, value)
}
```
I would like to make husky just use OTel for tracing, but some consumers are still using beeline and I don’t want to add beeline as a dependency. 
- Adds …

feat: Add tracing support

---

otlp/common.go
otlp/common_test.go
otlp/logs.go
otlp/traces.go

- Highly compressed payloads could cause memory pressure because of unchecked sizes in the reader.
- applies a LimitReader with a default of 20MiB

fix: Ensure a limited reader is used when decompressing payloads

---

go.mod

The following warning is triggered by CodeQL scanning: "As of Go 1.21, toolchain versions must use the 1.N.P syntax." as per https://go.dev/doc/toolchain#version
- updated go.mod file to include the patch version as well. used .0 to remain compatible with all versions of go 1.21

maint: appease codeql warning

---

otlp/common.go
otlp/logs.go
otlp/logs_test.go
otlp/traces.go
otlp/traces_test.go

Removes the unused `Batch.SizeBytes` property.
- remove unused batch.SizeBytes (we only use result.RequetSize)

chore: Remove SizeBytes from Batch struct

---

otlp/common.go
otlp/common_test.go
otlp/logs.go
otlp/logs_test.go
otlp/traces.go
otlp/traces_test.go

- closes #274 
- move sample rate logic that was in `traces` to `common`, including test cases
- add `sampleRate` to log events
- make `sampleRate` key name case-insensitive
- fall back to default rate of 1 when given negative values 
- round and coerce floats into ints
It would be nice to have an error if an invalid sampleRateKey is found. Right now we just return empty string.

feat: add sample rate to logs if set

---

otlp/common.go
otlp/traces_test.go

- lack of visibility into php library usage
- add PHP instrumentation library prefix 
- fix typo in test for `telemetry.instrumentation_name`

feat: add PHP to list of telemetry libraries

---

CHANGELOG.md
version.go

- prepare for v0.31.0 release
- update version.go
- update CHANGELOG.md entries

maint: prepare for release v0.31.0

---

otlp/common.go
otlp/common_test.go

- We had a function that was supposed to return the sampleRate key being used, but instead it always returned `sampleRate`, which broke things that didn't use that exact case.
- Return the actual key in use
- Adjust the test to use it

fix: Return the actual key from getSampleRateKey

---

CHANGELOG.md
version.go

- release the revert back to "(s|S)ampleRate only" behavior (#284)
- version bumped
- changelog updated

rel: prepare v0.33.0

---

otlp/common.go
otlp/common_test.go

Husky JSON encodes attribute values in certain circumstances (eg deeply nested attributes). However, by default the JSON encoder escapes HTML characters which makes using the values more difficult later.
This change updates the JSON encoder to not escape HTML characters.
- Disable HTML escaping in the JSON encoder by calling `SetEscapeHTML(false)`
- Add unit test to verify an attribute that contains HTML is not escaped

fix: Disable HTML escaping when JSON encoding values

---

otlp/logs.go
otlp/logs_test.go
otlp/traces.go
otlp/traces_test.go

When passing Husky Traces or Logs OTLP/HTTP request bodies, Husky currently defaults to a max request body size of 20MiB when the body is parsed. This can cause parsing issues if Husky is passed a file larger than 20MiB that contains batched trace or log telemetry within a single file. OTel collector batch processor configurations can reasonably exceed this limit for single files.
This PR creates some flexibility for the caller to define that limit while still [guarding against zipbombs](https://github.com/honeycombio/husky/pull/265) and maintaining existing functionality.
- Adds two new functions, `TranslateTraceRequestFromReaderSized` and `TranslateLogsRequestFromReaderSized` that allows a maxSize argument to be passed in
- Wraps `TranslateTraceRequestFromReader` and …

feat: Allow OTLP/HTTP request translation to be provided max request body size

---

CHANGELOG.md
version.go

- Prepares the v0.35.0 release.
- Update version to 0.35.0
- Add change log entry

maint: prepare for release v0.35.0

---

go.mod
go.sum
otlp/traces.go
otlp/traces_direct.go
otlp/traces_direct_json.go
otlp/traces_direct_test.go
otlp/traces_test.go

JSON is still a thing even in 2025 - some SDKs ONLY support sending the JSON flavor of OTLP. We'll need to handle this efficiently.
This extends the work in #307 with a JSON version mirroring the proto version. It's not great to have, in effect, two copies of the same business logic, but I think the language gymnastics we'd have to do to consolidate it between both implementations in an efficient way would make the code truly impenetrable. We'll have to have a lot of faith in our testing - `TestUnmarshalTraceRequestDirect_Complete` now includes JSON.
I'm using fastjson because jsoniter doesn't actually support zero-allocation object iteration. Unfortunately both libraries appear to be abandonware, with no modern alternative on the horizon.
This is much slower than protobuf, but that's to …

feat: support JSON OTLP in new fast path

---

otlp/traces.go
otlp/traces_direct.go
otlp/traces_direct_test.go

TranslateTraceRequestFromReaderSizedWithMsgp is designed for HTTP endpoints, where you have a reader and a content type. In GRPC-land, you're handed an already-read []byte which is assumed to be protobuf, so we can skip a level of indirection and buffering if we go directly to the unmarshal function for GRPC requests.
Just renames the function.

feat: export UnmarshalTraceRequestDirectMsgp

---

otlp/traces_direct_json.go
otlp/traces_direct_test.go

In [otel-js](https://github.com/open-telemetry/opentelemetry-js/blob/3dc89794a819a3a30fa40b0287eede691f15fb04/experimental/packages/otlp-transformer/src/common/internal.ts#L62), a `intValue` field is set with a number value not as a string. We should handle handle `intValue` field value as a int value as well.
- Add unit tests to make sure we return an error whenever there's a parsing error
- parse `intValue` as either a number or a string

fix: parse intValue from json as either a number or a string

---

otlp/common.go
otlp/common_test.go

- We were encountering a nil pointer exception when processing log data. The exception occurred on line 456 of `addAttributeToMap` when attempting to call methods on a `nil` `entry.value`. ([Sentry issue](https://honeycomb.sentry.io/issues/6633918091/?alert_rule_id=14802393&alert_timestamp=1758951911828&alert_type=email&environment=production&notification_uuid=fd589003-cd01-440b-aba1-0005408deee1&project=4505903518777344&referrer=alert_email))
- I just added a couple nil checks before we attempt further processing of the value.

fix(otlp): fix nil pointer in addAttributeToMap
