- CHANGELOG.md
- RELEASING.md
Adds a changelog and releasing docs.
- Add CHANGELOG file
- Add RELEASING file
> Add changelog & releasing docs

- otlp/common_test.go
Adds tests for checking case insensitivity when parsing headers into the `RequestInfo` struct.
- Adds case insensitivity tests
> Add case insensitive tests for parsing headers

- CHANGELOG.md
Prepares the v0.3.0 release.
- Adds changelog entry for v0.3.0
> Prepare v0.3.0 release notes

- CHANGELOG.md
> Prepare v0.4.0 release

- CHANGELOG.md
> Prepare v0.5.0 release

- CHANGELOG.md
- version.go
Prepares the v0.6.0 release.
- Updates version to `0.6.0` in version.go
> Prepare v0.6.0 release

- CHANGELOG.md
- version.go
> prepare 0.7.0 release

- CHANGELOG.md
- version.go
> prepare 0.8.0 release

- CHANGELOG.md
- version.go
> prepare 0.8.1 release

- CHANGELOG.md
- version.go
> Prepare 1.9.0 release

- CHANGELOG.md
- version.go
> Prepare 0.10.0

- CHANGELOG.md
- version.go
Prepeares the v0.10.1 release.
- Updates version to v0.10.1
> Prepare v0.10.1 release

- CHANGELOG.md
- version.go
> prepare 0.10.3 release

- .circleci/config.yml
- go.mod
Update go to latest version.
- Updates go to v1.18 in both go.mod and circle CI image used to build binaries
> Update go to 1.18

- CHANGELOG.md
- version.go
- Fixes in main that are unreleased!
- Bump version in version.go
- Update CHANGELOG
> prepare 0.10.6 release

- CHANGELOG.md
- version.go
Prepares the v0.11.0 release.
- Updates version to 0.11.0
> Prepare 0.11.0 release

- CHANGELOG.md
- version.go
Prepares the v0.11.1 release.
- Updates version to 0.11.1
> Prepare v0.11.1 release

- CHANGELOG.md
- version.go
Prepares the v0.11.2 release.
- Updates version to v0.11.2
> Prepare 0.11.2 release

- CHANGELOG.md
- version.go
Prepares the v0.12.0 release
- Closes https://github.com/honeycombio/telemetry-team/issues/293
- Updates version to 0.12.0
> Prepare v0.12.0 release

- CHANGELOG.md
- version.go
Prepares the v0.13.0 release.
- Updates version to 0.13.0
> Prepare 0.13.0 release

- CHANGELOG.md
- version.go
Prepares release 0.13.1
- Updated version to 0.13.1
- Added changelog entry
> Prepare release 0.14.0

- CHANGELOG.md
- version.go
Prepares the v0.15.0 release.
- Updates version to v0.15.0
> Prepare v0.15.0 release

- CHANGELOG.md
- version.go
- Shipping thingzzzz
- Bump 'n' Log
> [release] Prepare v0.16.0

- CHANGELOG.md
- version.go
Prepares the v0.16.1 release.
- Updates version to 0.16.1
> Prepare v0.16.1 release

- CHANGELOG.md
- version.go
> Prep for release 0.17.0

- CHANGELOG.md
- version.go
- Release v.18.0
- Bump version
- Update changelog
> release: v0.18.0

- .github/dependabot.yml
Make dependabot titles work better
> chore: Make dependabot titles work better

- otlp/traces.go
This fixes https://github.com/honeycombio/husky/issues/155
Assuming we agree there's nothing wrong with doing this
> feat: Add error field to events/links on spans that are error spans

- .github/workflows/add-to-project-v2.yml
Updates the workflows to use the Collections project board.
> chore: update workflows to Collections team

- otlp/common.go
- otlp/traces_test.go
It's useful to know whether a span was created from an instrumentation library (eg OTel maintained library) or not (manual tracing or custom meter in app). This enables analysis of who is using which libraries and which libraries are most popular.
Using the library name and matching against a list of known prefixes allows us to detect an instrumentation library.
This PR updates the scope translation of OTLP data into a generic event to to test the scope's library name against a list of known prefixes. If detection returns `true`, it adds a new field `telemetry.instrumentation_field` to the list of returned attributes.
- Add known prefixes for java, python, .net, ruby, go and js
- Update  `common/getScopeAttributes` to test the library name against the prefixes
- If an instrumentation …
> feat: Detect if scope is from instrumentation library

- CHANGELOG.md
- version.go
Prepares the v0.20.0 release.
- Updates version to 0.20.0
> rel: Prepare v0.20.0 release

- CHANGELOG.md
- RELEASING.md
- version.go
This is the corrections to instrumentation library detection
> chore: prep 0.21.0 release

- CHANGELOG.md
- version.go
> rel: Prep v0.22.0

- CHANGELOG.md
- otlp/traces.go
- otlp/traces_test.go
- version.go
> rel: Prep v0.22.1

- CHANGELOG.md
- version.go
prepare for 0.22.3 release
- bump verions.txt
- update changelog
> rel: prepare 0.22.3 release

- CHANGELOG.md
- version.go
> rel: Prep for v0.22.4

- CHANGELOG.md
- version.go
> rel: Prep for release v0.24.0

- CHANGELOG.md
- version.go
Prepares the 0.25.0 release of husky.
- Update version to 0.25.0
> rel: Prepare v0.25.0 release

- CHANGELOG.md
- version.go
Prepares the v0.25.1 release.
- Update version to 0.25.1
> rel: Prepare v0.25.1 release

- CHANGELOG.md
- version.go
Prepares the v0.26.0 release.
- Update version to 0.26.0
> rel: prepare v0.26.0 release

- CHANGELOG.md
- version.go
Prepares the next release of Husky.
- Update version to 0.27.0
> rel: Prepare 0.27.0 release

- CHANGELOG.md
- version.go
Prepares the next release.
- Update version to 0.28.0
> rel: Prepare v0.28.0 release

- CHANGELOG.md
- version.go
Prepares the next release of the library for publishing.
- Update version to 0.29.0
> rel: Prepare 0.29.0 release

- CHANGELOG.md
- version.go
> rel: prep 0.32.0

- CHANGELOG.md
- version.go
Prepares the v0.34.0 release.
- Update version to 0.34.0
- Add change log entry
> rel: Prepare the v0.34.0 release

- CHANGELOG.md
- version.go
Prepare the v0.37.0 release.
- Update version to 0.37.0
> rel: Prepare v0.37.0 release

- CHANGELOG.md
- version.go
Prepares the next release of the package.
- Update version to v0.39.2
> rel: Prepare v0.39.2 release
